name: Build and Push Docker Images

on:
    push:
          branches:
                  - master

          jobs:
              build-and-push:
                    runs-on: ubuntu-latest

                          steps:
                                  - name: Checkout code
                                            uses: actions/checkout@v2

                                                    - name: Set up Docker Buildx
                                                              uses: docker/setup-buildx-action@v1

                                                                      - name: Log in to Amazon ECR
                                                                                id: login-ecr
                                                                                          uses: aws-actions/amazon-ecr-login@v1
                                                                                                    with:
                                                                                                                region: us-east-1

                                                                                                                        - name: Build and push MySQL image
                                                                                                                                  run: |
                                                                                                                                              docker build -t my-mysql:latest -f Dockerfile.mysql .
                                                                                                                                                        docker tag my-mysql:latest ${{ steps.login-ecr.outputs.registry }}/mysql:latest
                                                                                                                                                                  docker push ${{ steps.login-ecr.outputs.registry }}/mysql:latest

                                                                                                                                                                        - name: Build and push webapp image
                                                                                                                                                                                  run: |
                                                                                                                                                                                              docker build -t my-webapp:latest .
                                                                                                                                                                                                        docker tag my-webapp:latest ${{ steps.login-ecr.outputs.registry }}/webapp:latest
                                                                                                                                                                                                                  docker push ${{ steps.login-ecr.outputs.registry }}/webapp:latest

